/**
 * pack-win.js  –  Packages KYO Downloader for Windows
 * 
 * Steps:
 *   1. Run @electron/packager → dist-electron/KYO Downloader-win32-x64/
 *   2. Create Portable .exe using 7-Zip SFX
 *   3. Create NSIS installer script + compile if makensis is available
 * 
 * Run: node pack-win.js
 */

const { execSync, spawnSync } = require('child_process');
const fs   = require('fs');
const path = require('path');

const ROOT      = __dirname;
const OUT_DIR   = path.join(ROOT, 'dist-electron');
const APP_NAME  = 'KYO Downloader';
const VERSION   = '2.1.1';
const APP_DIR   = path.join(OUT_DIR, `${APP_NAME}-win32-x64`);
const ICON_PATH = path.join(ROOT, 'assets', 'icon.ico');

// ─── Helper ────────────────────────────────────────────────────────────────
function run(cmd, opts = {}) {
  console.log(`\n> ${cmd}`);
  try {
    execSync(cmd, { stdio: 'inherit', ...opts });
  } catch (e) {
    throw new Error(`Command failed: ${cmd}\n${e.message}`);
  }
}

function ensureDir(p) {
  if (!fs.existsSync(p)) fs.mkdirSync(p, { recursive: true });
}

// ─── Step 1: Package with @electron/packager ──────────────────────────────
function package_app() {
  console.log('\n══════════════════════════════════════════');
  console.log('  Step 1: Packaging with electron-packager');
  console.log('══════════════════════════════════════════');

  if (fs.existsSync(APP_DIR)) {
    console.log('Removing existing packaged dir...');
    fs.rmSync(APP_DIR, { recursive: true, force: true });
  }

  ensureDir(OUT_DIR);

  const iconFlag = fs.existsSync(ICON_PATH) ? `--icon="${ICON_PATH}"` : '';

  run(
    `npx @electron/packager . "${APP_NAME}" --platform=win32 --arch=x64 ` +
    `--out="${OUT_DIR}" --overwrite --asar ${iconFlag} ` +
    `--ignore="dist-electron" --ignore="node_modules" --ignore="\\.git"`,
    { cwd: ROOT }
  );

  if (!fs.existsSync(APP_DIR)) {
    throw new Error(`Packaging failed – ${APP_DIR} does not exist`);
  }
  console.log(`\n✅  App packaged to: ${APP_DIR}`);
}

// ─── Step 2: Create a simple .zip portable ────────────────────────────────
function create_portable_zip() {
  console.log('\n══════════════════════════════════════════');
  console.log('  Step 2: Creating Portable ZIP');
  console.log('══════════════════════════════════════════');

  const zipOut = path.join(OUT_DIR, `KYO-Downloader-${VERSION}-Portable-win64.zip`);
  if (fs.existsSync(zipOut)) fs.unlinkSync(zipOut);

  // Try PowerShell Compress-Archive (built into Windows)
  try {
    run(
      `powershell -ExecutionPolicy Bypass -Command ` +
      `"Compress-Archive -Path '${APP_DIR}\\*' -DestinationPath '${zipOut}' -Force"`,
      { cwd: ROOT }
    );
    console.log(`\n✅  Portable ZIP: ${zipOut}`);
    return zipOut;
  } catch (e) {
    console.warn('PowerShell zip failed, trying 7za...');
  }

  // Fallback: 7za bundled with electron-builder
  const sevenZa = path.join(ROOT, 'node_modules', '7zip-bin', 'win', 'x64', '7za.exe');
  if (fs.existsSync(sevenZa)) {
    run(`"${sevenZa}" a -tzip "${zipOut}" "${APP_DIR}\\*"`, { cwd: ROOT });
    console.log(`\n✅  Portable ZIP: ${zipOut}`);
    return zipOut;
  }

  console.warn('⚠  Could not create ZIP. Add the app folder manually.');
  return null;
}

// ─── Step 3: Create NSIS installer script ─────────────────────────────────
function create_nsis_installer() {
  console.log('\n══════════════════════════════════════════');
  console.log('  Step 3: Generating NSIS Installer');
  console.log('══════════════════════════════════════════');

  const nsisScript = path.join(OUT_DIR, 'installer.nsi');
  const exeOut     = path.join(OUT_DIR, `KYO-Downloader-${VERSION}-Setup-win64.exe`);
  const iconArg    = fs.existsSync(ICON_PATH) ? ICON_PATH.replace(/\//g, '\\') : '';

  const nsi = `
; KYO Downloader – NSIS Installer Script
; Generated by pack-win.js

Unicode True
!define APP_NAME     "${APP_NAME}"
!define VERSION      "${VERSION}"
!define PUBLISHER    "oziajayakan"
!define APP_DIR      "${APP_DIR.replace(/\//g, '\\')}"
!define OUT_EXE      "${exeOut.replace(/\//g, '\\')}"
${iconArg ? `!define ICON_FILE    "${iconArg}"` : ''}

Name "$\{APP_NAME} v$\{VERSION\}"
OutFile "$\{OUT_EXE\}"
InstallDir "$PROGRAMFILES64\\$\{APP_NAME\}"
InstallDirRegKey HKCU "Software\\$\{APP_NAME\}" ""
RequestExecutionLevel admin
SetCompressor /SOLID lzma

${iconArg ? 'Icon "${ICON_FILE}"' : ''}
${iconArg ? 'UninstallIcon "${ICON_FILE}"' : ''}

Page directory
Page instfiles
UninstPage uninstConfirm
UninstPage instfiles

Section "Install"
  SetOutPath "$INSTDIR"
  File /r "$\{APP_DIR\}\\*.*"

  ; Write uninstaller
  WriteUninstaller "$INSTDIR\\Uninstall.exe"

  ; Registry
  WriteRegStr HKCU "Software\\$\{APP_NAME\}" "" "$INSTDIR"
  WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\$\{APP_NAME\}" \\
    "DisplayName" "$\{APP_NAME\}"
  WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\$\{APP_NAME\}" \\
    "UninstallString" "$INSTDIR\\Uninstall.exe"
  WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\$\{APP_NAME\}" \\
    "DisplayVersion" "$\{VERSION\}"
  WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\$\{APP_NAME\}" \\
    "Publisher" "$\{PUBLISHER\}"

  ; Shortcuts
  CreateDirectory "$SMPROGRAMS\\$\{APP_NAME\}"
  CreateShortCut  "$SMPROGRAMS\\$\{APP_NAME\}\\$\{APP_NAME\}.lnk" \\
    "$INSTDIR\\$\{APP_NAME\}.exe"
  CreateShortCut  "$DESKTOP\\$\{APP_NAME\}.lnk" \\
    "$INSTDIR\\$\{APP_NAME\}.exe"

  MessageBox MB_OK "KYO Downloader berhasil diinstall!"
SectionEnd

Section "Uninstall"
  RMDir /r "$INSTDIR"
  Delete "$SMPROGRAMS\\$\{APP_NAME\}\\$\{APP_NAME\}.lnk"
  RMDir  "$SMPROGRAMS\\$\{APP_NAME\}"
  Delete "$DESKTOP\\$\{APP_NAME\}.lnk"
  DeleteRegKey HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\$\{APP_NAME\}"
  DeleteRegKey HKCU "Software\\$\{APP_NAME\}"
SectionEnd
`;

  fs.writeFileSync(nsisScript, nsi.trim());
  console.log(`\n✅  NSIS script: ${nsisScript}`);

  // Try compiling with makensis if available
  const makensis = [
    'C:\\Program Files (x86)\\NSIS\\makensis.exe',
    'C:\\Program Files\\NSIS\\makensis.exe',
    'makensis',
  ];

  for (const cmd of makensis) {
    try {
      if (!fs.existsSync(cmd) && cmd !== 'makensis') continue;
      run(`"${cmd}" "${nsisScript}"`);
      console.log(`\n✅  Installer: ${exeOut}`);
      return;
    } catch (e) { /* try next */ }
  }

  console.log('\n⚠  NSIS (makensis) not found on this system.');
  console.log('   To compile the installer, install NSIS from https://nsis.sourceforge.io/');
  console.log('   Then run:  makensis "' + nsisScript + '"');
  console.log('\n   The NSIS script has been saved to: ' + nsisScript);
}

// ─── Main ─────────────────────────────────────────────────────────────────
async function main() {
  console.log('╔══════════════════════════════════════════════╗');
  console.log('║  KYO Downloader – Windows Build Tool      ║');
  console.log('╚══════════════════════════════════════════════╝');

  try {
    package_app();
    create_portable_zip();
    create_nsis_installer();

    console.log('\n╔══════════════════════════════════════════════╗');
    console.log('║  BUILD SUMMARY                               ║');
    console.log('╚══════════════════════════════════════════════╝');
    console.log(`Output directory: ${OUT_DIR}`);
    const files = fs.readdirSync(OUT_DIR).filter(f => f.endsWith('.exe') || f.endsWith('.zip'));
    if (files.length) {
      files.forEach(f => console.log(`  ✅  ${f}`));
    } else {
      console.log('  (Check dist-electron/ for output)');
    }
  } catch (e) {
    console.error('\n❌  Build failed:', e.message);
    process.exit(1);
  }
}

main();
